export type DisclosureSearchFolder = {
  id: string;
  tab: "rules" | "meetings" | "administration" | "accounting" | "operations";
  tabLabel: string;
  title: string;
  description: string;
  date: string;
  subCategory: string;
  keywords?: string[];
};

export const disclosureSearchFolders: DisclosureSearchFolder[] = [
  {
    id: "rules-1",
    tab: "rules",
    tabLabel: "규약 및 연명부",
    title: "대방동 지역주택조합 정관 및 조합규약",
    description: "조합원의 의무와 권리, 총회·이사회 의결 절차 등 조합의 법적 운영 기준을 명세한 정관 문서입니다.",
    date: "2026.02",
    subCategory: "정관 및 조합규약",
    keywords: ["조합규약", "정관", "총회", "이사회", "분담금", "탈퇴"],
  },
  {
    id: "rules-3",
    tab: "rules",
    tabLabel: "규약 및 연명부",
    title: "운영관리규정",
    description: "사무국 운영, 민원 응대, 문서 접수·보존, 내부 결재와 정보공개 절차를 정리한 운영 기준입니다.",
    date: "2026.02",
    subCategory: "운영관리규정",
    keywords: ["사무국", "민원", "정보공개", "문서 접수", "문서 보존"],
  },
  {
    id: "rules-4",
    tab: "rules",
    tabLabel: "규약 및 연명부",
    title: "회계관리규정",
    description: "예산 편성, 자금 집행, 증빙 보관, 회계 보고와 감사 대응 절차를 정리한 회계 운영 기준입니다.",
    date: "2026.02",
    subCategory: "회계관리규정",
    keywords: ["예산", "자금 집행", "증빙", "회계", "감사"],
  },
  {
    id: "rules-5",
    tab: "rules",
    tabLabel: "규약 및 연명부",
    title: "선거관리규정",
    description: "임원 선출, 후보 등록, 투표·개표, 이의신청 절차를 공정하게 관리하기 위한 선거 기준입니다.",
    date: "2026.02",
    subCategory: "선거관리규정",
    keywords: ["임원", "후보", "투표", "개표", "이의신청"],
  },
  {
    id: "rules-6",
    tab: "rules",
    tabLabel: "규약 및 연명부",
    title: "기타 내부 운영규정",
    description: "조합 운영 중 별도 제정되는 보안, 개인정보, 협력사 관리 등 내부 규정을 한곳에서 관리합니다.",
    date: "수시 업데이트",
    subCategory: "기타 내부 운영규정",
    keywords: ["보안", "개인정보", "협력사", "내부 규정"],
  },
  {
    id: "rules-2",
    tab: "rules",
    tabLabel: "규약 및 연명부",
    title: "대방동지역주택조합 정식 조합원 연명부",
    description: "동작구청 설립인가 및 정식 등재 완료된 입주 예정 조합원 연명 목록입니다. 개인정보 비식별 조치 후 관리합니다.",
    date: "2025.12",
    subCategory: "조합원 연명부",
    keywords: ["연명부", "조합원 명부", "설립인가", "비식별"],
  },
  {
    id: "meetings-1",
    tab: "meetings",
    tabLabel: "의사록",
    title: "총회의사록 문서함",
    description: "창립총회 및 최근 임시총회 안건 의결 결과, 조합원 서명 날인 등이 기재된 정식 공증 의사록 문서 보존 문서함입니다.",
    date: "최근 업데이트: 2026.01",
    subCategory: "총회 의사록",
    keywords: ["총회", "총회의사록", "의사록", "공증", "안건", "의결"],
  },
  {
    id: "meetings-2",
    tab: "meetings",
    tabLabel: "의사록",
    title: "이사회 의사록 문서함",
    description: "사무국 예산 조율, 협력사 계약 심의 등 이사회 및 감사 정례 의결 의사록이 안전하게 일괄 보관되어 있습니다.",
    date: "최근 업데이트: 2026.01",
    subCategory: "이사회 의사록",
    keywords: ["이사회", "의사록", "계약 심의", "예산", "감사"],
  },
  {
    id: "meetings-3",
    tab: "meetings",
    tabLabel: "의사록",
    title: "대의원 의사록 문서함",
    description: "대의원회 안건 보고, 의결 결과, 참석자 확인 등 대의원 회의 관련 기록을 별도 보관하는 문서함입니다.",
    date: "최근 업데이트: 2026.01",
    subCategory: "대의원 의사록",
    keywords: ["대의원", "대의원회", "의사록", "안건", "의결"],
  },
  {
    id: "administration-1",
    tab: "administration",
    tabLabel: "공문서",
    title: "수신 공문서 문서함",
    description: "동작구청, 서울시 등 관청에서 조합으로 접수된 공식 수신 공문과 행정 실태조사 관련 수신자료를 보관합니다.",
    date: "최근 업데이트: 2026.01",
    subCategory: "공문서",
    keywords: ["수신", "공문", "공문서", "동작구청", "서울시", "관청", "실태조사", "행정 실태조사"],
  },
  {
    id: "administration-2",
    tab: "administration",
    tabLabel: "공문서",
    title: "발신 공문서 문서함",
    description: "조합에서 동작구청, 서울시 등 유관기관으로 제출한 발신 공문과 회신·조치결과 보고 문서를 보관합니다.",
    date: "최근 업데이트: 2026.01",
    subCategory: "공문서",
    keywords: ["발신", "회신", "공문", "공문서", "조치결과", "유관기관"],
  },
  {
    id: "administration-4",
    tab: "administration",
    tabLabel: "공문서",
    title: "기타 공문서 문서함",
    description: "수신 및 발신 분류에 속하지 않는 협조전, 보고서 및 기타 행정 서류를 보관합니다.",
    date: "최근 업데이트: 2026.01",
    subCategory: "공문서",
    keywords: ["기타", "공문", "공문서", "협조전", "보고서", "행정 서류"],
  },
  {
    id: "acc-1",
    tab: "accounting",
    tabLabel: "회계 및 감사",
    title: "정기 외부회계감사 보고서",
    description: "독립된 공인회계법인으로부터 분담금 집행 일체를 정밀 감사받은 결과보고서입니다.",
    date: "2026.02",
    subCategory: "회계감사보고서",
    keywords: ["회계", "감사", "외부감사", "분담금", "보고서"],
  },
  {
    id: "acc-3",
    tab: "accounting",
    tabLabel: "회계 및 감사",
    title: "연간 자금운용계획",
    description: "조합의 사업비 조달 및 집행, 예산 수립 관련 연간 전체 자금 운용 계획입니다.",
    date: "2026.01",
    subCategory: "연간자금운용계획",
    keywords: ["자금운용", "사업비", "예산", "집행", "자금"],
  },
  {
    id: "acc-4",
    tab: "accounting",
    tabLabel: "회계 및 감사",
    title: "월별 자금 입출금 명세서",
    description: "신탁사 수탁 계좌를 통해 안전하게 집행된 월별 자금 입출금 세부 명세서입니다.",
    date: "2026.02",
    subCategory: "월별 자금 입출금",
    keywords: ["월별", "자금", "입출금", "신탁사", "명세서"],
  },
  {
    id: "acc-5",
    tab: "accounting",
    tabLabel: "회계 및 감사",
    title: "조합원 분담금 납부 현황",
    description: "전체 조합원의 분담금 납부 현황 및 미납금 관리 내역입니다.",
    date: "수시 업데이트",
    subCategory: "분담금 납부",
    keywords: ["조합원", "분담금", "납부", "미납금"],
  },
  {
    id: "acc-6",
    tab: "accounting",
    tabLabel: "회계 및 감사",
    title: "추가 분담금 산출 명세서",
    description: "사업비 변경 등에 따른 추가 분담금 발생 여부 및 산출 근거 자료입니다.",
    date: "수시 업데이트",
    subCategory: "추가 분담금 산출",
    keywords: ["추가 분담금", "사업비", "산출", "명세서"],
  },
  {
    id: "ops-6",
    tab: "operations",
    tabLabel: "사업, 계약 및 감리",
    title: "토지 사용권원 및 소유권 확보 비율 명세서",
    description: "토지 사용권원 및 소유권 확보 비율을 공개합니다.",
    date: "수시 업데이트",
    subCategory: "토지확보",
    keywords: ["토지", "사용권원", "소유권", "확보", "비율"],
  },
  {
    id: "ops-1",
    tab: "operations",
    tabLabel: "사업, 계약 및 감리",
    title: "설계·용역·부동산 대행사별 정식 계약서 원본 일람",
    description: "하우드엔지니어링, 매입, 법률 등 조합이 정식 체결하고 공증한 일체의 계약서 모음입니다.",
    date: "2025.07",
    subCategory: "용역 계약서",
    keywords: ["설계", "용역", "부동산", "계약서", "하우드엔지니어링", "법률"],
  },
  {
    id: "ops-7",
    tab: "operations",
    tabLabel: "사업, 계약 및 감리",
    title: "사업시행계획서 문서함",
    description: "대방동 11-103 일대 주택건설 사업계획서 및 지구단위계획 결정 고시 등 인허가 원본 문서입니다.",
    date: "최근 업데이트: 2025.08",
    subCategory: "사업시행계획",
    keywords: ["사업시행계획", "사업계획서", "지구단위계획", "결정 고시", "인허가"],
  },
  {
    id: "ops-2",
    tab: "operations",
    tabLabel: "사업, 계약 및 감리",
    title: "공사시행 및 월별 공사진행 보고서",
    description: "월별 공사진행 상황에 관한 서류입니다.",
    date: "2026.02",
    subCategory: "공사시행",
    keywords: ["공사", "공사진행", "월별", "보고서"],
  },
  {
    id: "ops-3",
    tab: "operations",
    tabLabel: "사업, 계약 및 감리",
    title: "분기별 사업실적보고서",
    description: "지구단위계획 완수 이후 소방·설비 설계 용역사 발주 등 단계별 마일스톤 도달 실적에 대한 조합 공식 보고입니다.",
    date: "2025.09",
    subCategory: "실적보고서",
    keywords: ["분기", "사업실적", "실적보고서", "소방", "설비"],
  },
  {
    id: "ops-4",
    tab: "operations",
    tabLabel: "사업, 계약 및 감리",
    title: "건축·소방 감리원 안전점검 및 월간 감리보고서",
    description: "인허가 관련 정밀 안전 확보와 법령 준수를 위해 감리 기술자가 정밀 점검하고 관청에 제출한 공식 실적서입니다.",
    date: "2025.11",
    subCategory: "감리 보고서",
    keywords: ["건축", "소방", "감리", "안전점검", "월간", "보고서"],
  },
  {
    id: "ops-8",
    tab: "operations",
    tabLabel: "사업, 계약 및 감리",
    title: "분양신청 및 관련 자료 문서함",
    description: "분양신청에 관한 서류 및 관련 자료로 구성되어 있습니다.",
    date: "수시 업데이트",
    subCategory: "분양",
    keywords: ["분양", "분양신청", "관련 자료"],
  },
];
